name: Firebase CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📦 Checkout source code
        uses: actions/checkout@v4

      - name: ⚙️ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: |
            backend/functions/package-lock.json


      - name: 🚀 Install Functions dependencies
        working-directory: ./backend/functions
        run: |
          npm ci

      - name: 🛠️ Install Firebase CLI
        run: npm install -g firebase-tools

      - name: 🔐 Create .env for Cloud Functions
        working-directory: ./backend/functions
        run: |
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" > .env

      - name: ☁️ Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --project dhanyavahini-4d360 --only functions,firestore,storage --token "$FIREBASE_TOKEN" --force --non-interactive
